In [34]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.decomposition import PCA

In [2]:
pwd

u'/home/hao/Repos/DSI/DOTA2_Recommendation-System/notebook'

In [3]:
cd ..

/home/hao/Repos/DSI/DOTA2_Recommendation-System

In [4]:
df = pd.read_csv('file/hero_attributes', sep='t',index_col=0)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110 entries, 0 to 110
Data columns (total 23 columns):
HERO        110 non-null object
ATT         110 non-null object
STR         110 non-null int64
STR+        110 non-null float64
AGI         110 non-null int64
AGI+        110 non-null float64
INT         110 non-null int64
INT+        110 non-null float64
T+          110 non-null float64
LVL25       110 non-null float64
MOV         110 non-null int64
AR          110 non-null float64
DMG(MIN)    110 non-null int64
DMG(MAX)    110 non-null int64
RNG         110 non-null int64
BAT         110 non-null float64
ATKPT       110 non-null float64
ATKBS       110 non-null float64
VIS-D       110 non-null object
VIS-N       110 non-null object
TURN        110 non-null float64
COLL        110 non-null int64
HP/S        110 non-null float64
dtypes: float64(11), int64(8), object(4)
memory usage: 20.6+ KB

In [6]:
df.head()

,HERO,ATT,STR,STR+,AGI,AGI+,INT,INT+,T+,LVL25,...,DMG(MAX),RNG,BAT,ATKPT,ATKBS,VIS-D,VIS-N,TURN,COLL,HP/S
0,Abaddon,Strength,23,2.7,17,1.5,21,2.0,6.2,216.0,...,65,128,1.70,0.56,0.41,"1,800",800,0.6,24,0.25
1,Alchemist,Strength,25,1.8,11,1.2,25,1.8,4.8,181.0,...,58,128,1.70,0.35,0.65,"1,800",800,0.6,24,0.25
2,Ancient Apparition,Intelligence,18,1.4,20,2.2,25,2.6,6.2,218.0,...,54,600,1.70,0.45,0.30,"1,800",800,0.6,24,0.25
3,Anti-Mage,Agility,22,1.2,22,2.8,15,1.8,5.8,204.0,...,53,128,1.45,0.30,0.60,"1,800",800,0.5,24,0.25
5,Axe,Strength,25,2.5,20,2.2,18,1.6,6.3,220.5,...,53,128,1.70,0.50,0.50,"1,800",800,0.6,24,3.00

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
STR,110,19.909091,3.263772,14.00,17.0000,19.50,22.7500,29.00
STR+,110,2.163636,0.533764,1.00,1.8000,2.10,2.5000,3.80
AGI,110,17.909091,4.510020,9.00,15.0000,18.00,21.0000,34.00
AGI+,110,1.953636,0.618770,0.80,1.5000,1.90,2.2875,3.40
INT,110,19.363636,4.087859,13.00,16.0000,18.00,22.0000,28.00
INT+,110,2.144545,0.634929,1.00,1.6625,2.00,2.6000,4.00
T+,110,6.261818,0.550060,4.80,6.0000,6.20,6.6000,7.70
LVL25,110,213.727273,14.536357,181.00,205.0000,213.75,221.0000,252.50
MOV,110,300.727273,12.169227,270.00,290.0000,300.00,310.0000,335.00
AR,110,2.698182,1.729985,-0.46,1.2700,2.40,3.7500,7.96
DMG(MIN),110,47.527273,7.626257,29.00,43.0000,46.50,51.0000,81.00
DMG(MAX),110,55.500000,8.363036,31.00,50.2500,55.00,60.7500,89.00
RNG,110,338.345455,213.192054,128.00,128.0000,350.00,550.0000,700.00
BAT,110,1.694091,0.070298,1.40,1.7000,1.70,1.7000,2.00
ATKPT,110,0.420300,0.115724,0.15,0.3075,0.40,0.5000,0.75
ATKBS,110,0.561264,0.193669,0.00,0.4475,0.54,0.7000,1.17
TURN,110,0.556818,0.141337,0.40,0.5000,0.50,0.6000,1.00
COLL,110,23.563636,2.617959,8.00,24.0000,24.00,24.0000,24.00
HP/S,110,0.418182,0.538760,0.25,0.2500,0.25,0.2500,3.50

In [8]:
df.head(1).T

                 0
HERO       Abaddon
ATT       Strength
STR             23
STR+           2.7
AGI             17
AGI+           1.5
INT             21
INT+             2
T+             6.2
LVL25          216
MOV            310
AR            1.38
DMG(MIN)        55
DMG(MAX)        65
RNG            128
BAT            1.7
ATKPT         0.56
ATKBS         0.41
VIS-D        1,800
VIS-N          800
TURN           0.6
COLL            24
HP/S          0.25

In [9]:
df_hero = df.copy(deep=True)

In [11]:
df_hero.drop(['HERO', 'ATT'], axis=1, inplace=True)

In [12]:
df_hero.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110 entries, 0 to 110
Data columns (total 21 columns):
STR         110 non-null int64
STR+        110 non-null float64
AGI         110 non-null int64
AGI+        110 non-null float64
INT         110 non-null int64
INT+        110 non-null float64
T+          110 non-null float64
LVL25       110 non-null float64
MOV         110 non-null int64
AR          110 non-null float64
DMG(MIN)    110 non-null int64
DMG(MAX)    110 non-null int64
RNG         110 non-null int64
BAT         110 non-null float64
ATKPT       110 non-null float64
ATKBS       110 non-null float64
VIS-D       110 non-null object
VIS-N       110 non-null object
TURN        110 non-null float64
COLL        110 non-null int64
HP/S        110 non-null float64
dtypes: float64(11), int64(8), object(2)
memory usage: 18.9+ KB

In [26]:
df_hero[['VIS-D', 'VIS-N']] = df_hero[['VIS-D', 'VIS-N']].applymap(lambda x: int(x.replace(',', '')))

In [29]:
min_max_scaler = preprocessing.MinMaxScaler()

In [32]:
df_hero = df_hero.apply(lambda x: min_max_scaler.fit_transform(x), axis=1)

### Kmeans clustering without PCA

In [35]:
from sklearn.cluster import KMeans

In [ ]:
Kmeans